#!/usr/bin/env python3
"""Link reading-list bullet heads to their footnote's own URL (W0c).

docs/plans/readability/report-C.md finding C1; docs/plans/readability-guide.md
R-LINKS rule 1 (steps 1-4); docs/plans/citation-style.md rule 5.

Inside ``## References`` only, per bullet under a ``* `` list item:

1. One marker ``[^k]``, and the text before the first `` — `` (the *head*)
   has no ``{role}``, ``[`` or backtick: wrap the whole head as
   ``[head](<URL>)``, URL = the first ``<URL>`` in the page's own
   ``[^k]:`` definition (character for character; when that definition's
   first URL is a Wayback capture, that is the URL used — the archive-first
   form is already page policy, R-WAYBACK).
2. Head has a role or backtick but exactly one ``*italic title*``: link
   only that span.
3. N markers and exactly N italic titles in the same order: link title
   *i* to marker *i*'s URL.
4. Anything else (no dash, no marker, marker undefined, ambiguous
   italics, already linked): leave the bullet untouched.

The marker always stays, unchanged, at the end of the bullet. Nothing
else in the bullet, the annotation after the dash, the number of
bullets, footnote definitions or the generated ``index-links`` block is
touched. A bullet inside a ``{dropdown}`` (an in-force patent note) is
left untouched by this script -- report-C.md and R-LINKS allow
converting it in place, but only "if `tools/check_inforce.py` still
passes" and "if in doubt, leave it": `check_preserved.py` treats any
change to a dropdown's body as a content edit needing a deliberate
`--allow-dropdown-edits`, so converting these by script would need a
per-page review this tool cannot do. Left as a documented hand-finish
candidate (reason ``in-dropdown``).

Idempotent: a bullet whose head already contains a markdown link
(``](<...`` before the dash) is left alone, so running this script
twice makes no further change.

Usage::

    uv run tools/fix_reading_list_links.py [--check] [path ...]
    uv run tools/fix_reading_list_links.py --selftest

With no paths, every ``docs/**/*.md`` file outside ``docs/plans`` is
processed. ``--check`` reports what would change (file, counts) without
writing, and exits non-zero if anything would change. Without
``--check``, matching files are rewritten in place and a summary is
printed.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"

sys.path.insert(0, str(Path(__file__).resolve().parent))
import check_inforce  # noqa: E402  (for its {dropdown} fence parser)

DEF_RE = re.compile(
    r"^\[\^([A-Za-z0-9_-]+)\]:(.*?)(?=^\[\^[A-Za-z0-9_-]+\]:|\Z)", re.M | re.S
)
MARK_RE = re.compile(r"\[\^([A-Za-z0-9_-]+)\]")
URL_RE = re.compile(r"<(https?://[^<>\s]+)>")
REFS_SECTION_RE = re.compile(r"^## References\n(.*?)(?=^## |\Z)", re.S | re.M)
# A single-asterisk italic span: never a run of "**bold**" (an opening or
# closing "*" adjacent to another "*"), and never whitespace directly
# inside the delimiters (CommonMark forbids it, and it is what would
# otherwise let a list bullet's own leading "* " be mistaken for an
# opening delimiter).
ITALIC_RE = re.compile(r"(?<!\*)\*(?![\s*])[^*]+?(?<![\s*])\*(?!\*)")
HEAD_TAIL_RE = re.compile(r"\A(\* .*?)(\s+—\s)", re.S)
GENBLOCK_RE = re.compile(
    r"<!-- index-links:begin \(generated by tools/gen_index_links\.py; "
    r"do not edit\) -->.*?<!-- index-links:end -->",
    re.S,
)

REASONS = (
    "ok-rule1",
    "ok-rule2",
    "ok-rule3",
    "already-linked",
    "in-dropdown",
    "no-dash",
    "no-marker",
    "no-url",
    "role-in-head",
    "multi-marker",
)


def page_urls(text: str) -> dict[str, str]:
    """``{label: first <URL> in that label's own [^label]: definition}``."""
    urls: dict[str, str] = {}
    for lab, body in DEF_RE.findall(text):
        found = URL_RE.findall(body)
        if found:
            urls[lab] = found[0]
    return urls


def convert_bullet(bullet: str, urls: dict[str, str]) -> tuple[str | None, str]:
    """Return ``(new_bullet_or_None, reason)`` for one ``* ...`` bullet.

    ``bullet`` is the bullet's own text (starting with ``* ``, no
    trailing blank line). Returns ``None`` with the reason it was left
    alone, or the rewritten bullet text with a reason starting "ok-".
    """
    m = HEAD_TAIL_RE.match(bullet)
    if not m:
        return None, "no-dash"
    head = m.group(1)[2:]  # drop the leading "* "
    tail = bullet[m.end(1) :]
    if "](<" in head:
        return None, "already-linked"
    labs = MARK_RE.findall(bullet)
    if not labs:
        return None, "no-marker"

    if len(labs) == 1:
        lab = labs[0]
        if lab not in urls:
            return None, "no-url"
        url = urls[lab]
        if "{" in head or "[" in head or "`" in head:
            italics = ITALIC_RE.findall(head)
            if len(italics) != 1 or "{" in italics[0]:
                return None, "role-in-head"
            new_head = head.replace(italics[0], f"[{italics[0]}](<{url}>)", 1)
            return "* " + new_head + tail, "ok-rule2"
        new_head = f"[{head}](<{url}>)"
        return "* " + new_head + tail, "ok-rule1"

    # Rule 3: N markers, N italic titles, same order.
    italics = list(ITALIC_RE.finditer(head))
    if len(italics) != len(labs):
        return None, "multi-marker"
    if any(lab not in urls for lab in labs):
        return None, "no-url"
    pieces: list[str] = []
    pos = 0
    for it, lab in zip(italics, labs):
        pieces.append(head[pos : it.start()])
        pieces.append(f"[{it.group(0)}](<{urls[lab]}>)")
        pos = it.end()
    pieces.append(head[pos:])
    new_head = "".join(pieces)
    return "* " + new_head + tail, "ok-rule3"


def process_text(text: str) -> tuple[str, dict[str, int]]:
    """Convert every eligible bullet under ``## References``.

    Returns ``(new_text, counts)`` where ``counts`` maps each reason (see
    ``REASONS``) to how many bullets fell into it. ``new_text`` is
    byte-identical to ``text`` when no bullet is converted.
    """
    counts: dict[str, int] = {}
    urls = page_urls(text)
    rm = REFS_SECTION_RE.search(text)
    if not rm:
        return text, counts
    section = rm.group(1)
    # Defensive: never touch the generated block, though it never sits
    # inside "## References" on this site (checked; it always precedes it).
    if GENBLOCK_RE.search(section):
        raise SystemExit(
            "fix_reading_list_links: found a generated index-links block "
            "inside '## References' -- refusing to touch this page"
        )
    dropdown_lines = check_inforce.dropdown_lines(text)
    base_lines = text[: rm.start(1)].count("\n")
    # Split at the single "\n" that separates two top-level bullets (the
    # prototype's boundary): a tight list has no blank line between
    # bullets, only between the last bullet of a tier and its heading. The
    # delimiter itself (one "\n") is dropped by split and put back below.
    chunks = re.split(r"\n(?=\* )", section)
    out: list[str] = []
    offset = 0
    for idx, chunk in enumerate(chunks):
        if idx > 0:
            offset += 1  # the "\n" delimiter consumed by split, restored
        if chunk.startswith("* "):
            # A bullet's own text ends at the first blank line, if any
            # (the tier heading that may follow it); anything from there
            # on is passed through untouched.
            bullet, sep, rest = chunk.partition("\n\n")
            abs_line = base_lines + section[:offset].count("\n") + 1
            if abs_line in dropdown_lines:
                new, reason = None, "in-dropdown"
            else:
                new, reason = convert_bullet(bullet, urls)
            counts[reason] = counts.get(reason, 0) + 1
            chunk_out = (new if new is not None else bullet) + sep + rest
        else:
            chunk_out = chunk
        out.append(chunk_out if idx == 0 else "\n" + chunk_out)
        offset += len(chunk)
    new_section = "".join(out)
    new_text = text[: rm.start(1)] + new_section + text[rm.end(1) :]
    return new_text, counts


def target_files(paths: list[str]) -> list[Path]:
    if paths:
        return [Path(p).resolve() for p in paths]
    return sorted(
        p
        for p in DOCS.rglob("*.md")
        if "plans" not in p.relative_to(DOCS).parts
        and "references" not in p.relative_to(DOCS).parts
    )


def run(paths: list[str], check: bool) -> int:
    total: dict[str, int] = {}
    changed_files: list[Path] = []
    for path in target_files(paths):
        text = path.read_text(encoding="utf-8")
        new_text, counts = process_text(text)
        for k, v in counts.items():
            total[k] = total.get(k, 0) + v
        if new_text != text:
            changed_files.append(path)
            if not check:
                path.write_text(new_text, encoding="utf-8")
    ok_total = sum(v for k, v in total.items() if k.startswith("ok-"))
    print(f"{len(changed_files)} files {'would change' if check else 'changed'}")
    print(f"converted: {ok_total}  ({', '.join(f'{k}={v}' for k, v in sorted(total.items()) if k.startswith('ok-'))})")
    left = {k: v for k, v in total.items() if not k.startswith("ok-")}
    print(f"left alone: {sum(left.values())}  ({', '.join(f'{k}={v}' for k, v in sorted(left.items()))})")
    if check:
        for f in changed_files:
            print(f"would change: {f.relative_to(ROOT)}")
        return 1 if changed_files else 0
    return 0


# --------------------------------------------------------------------------


def selftest() -> int:
    problems: list[str] = []

    def fail(msg: str) -> None:
        problems.append(msg)

    def refs(bullets: str, defs: str) -> str:
        return f"# T\n\n## References\n\n### Deep dive\n\n{bullets}\n{defs}"

    # Rule 1: plain head, single marker.
    page = refs(
        "* Wikipedia, *Shallow trench isolation* — the three STI operations "
        "and the LOCOS cross-over node.[^wiki-sti]\n",
        "[^wiki-sti]: Wikipedia, *Shallow trench isolation*. "
        "<https://en.wikipedia.org/wiki/Shallow_trench_isolation>\n",
    )
    new, counts = process_text(page)
    if counts.get("ok-rule1") != 1:
        fail(f"rule 1 did not fire: {counts}")
    if "[Wikipedia, *Shallow trench isolation*](<https://en.wikipedia.org/wiki/Shallow_trench_isolation>)" not in new:
        fail(f"rule 1 produced the wrong head: {new!r}")
    if "the LOCOS cross-over node.[^wiki-sti]" not in new:
        fail(f"rule 1 dropped the trailing marker or the annotation: {new!r}")
    # Idempotent.
    new2, counts2 = process_text(new)
    if new2 != new:
        fail("rule 1 output is not idempotent")
    if counts2.get("already-linked") != 1:
        fail(f"the second pass did not recognise the link: {counts2}")

    # Rule 2: role/backtick in head, exactly one italic title.
    page = refs(
        "* SkyWater PDK, {ref}`Periphery rules <mask-periph>`, *Design rule "
        "manual* — the periphery constraints.[^pdk-periph]\n",
        "[^pdk-periph]: SkyWater PDK Authors, *Design rule manual*. "
        "<https://example.com/periph>\n",
    )
    new, counts = process_text(page)
    if counts.get("ok-rule2") != 1:
        fail(f"rule 2 did not fire: {counts}")
    if "[*Design rule manual*](<https://example.com/periph>)" not in new:
        fail(f"rule 2 linked the wrong span: {new!r}")
    if "{ref}`Periphery rules <mask-periph>`" not in new:
        fail("rule 2 touched the {ref} role")

    # Rule 3: N markers, N italic titles, in order.
    page = refs(
        "* Wikipedia, *Silane*, *Tetraethyl orthosilicate* and *Nitrogen "
        "trifluoride* — the precursors and the clean "
        "gas.[^wiki-silane][^wiki-teos][^wiki-nf3]\n",
        "[^wiki-silane]: Wikipedia, *Silane*. <https://en.wikipedia.org/wiki/Silane>\n"
        "[^wiki-teos]: Wikipedia, *Tetraethyl orthosilicate*. "
        "<https://en.wikipedia.org/wiki/Tetraethyl_orthosilicate>\n"
        "[^wiki-nf3]: Wikipedia, *Nitrogen trifluoride*. "
        "<https://en.wikipedia.org/wiki/Nitrogen_trifluoride>\n",
    )
    new, counts = process_text(page)
    if counts.get("ok-rule3") != 1:
        fail(f"rule 3 did not fire: {counts}")
    for title, url in (
        ("*Silane*", "https://en.wikipedia.org/wiki/Silane"),
        ("*Tetraethyl orthosilicate*", "https://en.wikipedia.org/wiki/Tetraethyl_orthosilicate"),
        ("*Nitrogen trifluoride*", "https://en.wikipedia.org/wiki/Nitrogen_trifluoride"),
    ):
        if f"[{title}](<{url}>)" not in new:
            fail(f"rule 3 did not link {title} to {url}: {new!r}")
    if "[^wiki-silane][^wiki-teos][^wiki-nf3]" not in new:
        fail("rule 3 disturbed the marker order")

    # Rule 3 across a wrapped line: an italic title split by the text
    # wrapping (docs/machines/pecvd.md:470-471) is still one title.
    page = refs(
        "* Wikipedia, *Silane*, *Tetraethyl orthosilicate* and *Nitrogen\n"
        "  trifluoride* — the precursors and the clean "
        "gas.[^wiki-silane][^wiki-teos][^wiki-nf3]\n",
        "[^wiki-silane]: Wikipedia, *Silane*. <https://en.wikipedia.org/wiki/Silane>\n"
        "[^wiki-teos]: Wikipedia, *Tetraethyl orthosilicate*. "
        "<https://en.wikipedia.org/wiki/Tetraethyl_orthosilicate>\n"
        "[^wiki-nf3]: Wikipedia, *Nitrogen trifluoride*. "
        "<https://en.wikipedia.org/wiki/Nitrogen_trifluoride>\n",
    )
    new, counts = process_text(page)
    if counts.get("ok-rule3") != 1:
        fail(f"rule 3 did not fire across a wrapped line: {counts}")
    if "[*Nitrogen\n  trifluoride*](<https://en.wikipedia.org/wiki/Nitrogen_trifluoride>)" not in new:
        fail(f"rule 3 mishandled a title wrapped across a line break: {new!r}")

    # A "**bold**" run in the head is never mistaken for an italic title.
    page = refs(
        "* **Loud Corp** and *Quiet Co* — two vendors.[^loud][^quiet]\n",
        "[^loud]: Loud Corp. <https://example.com/loud>\n"
        "[^quiet]: Quiet Co, *Quiet Co*. <https://example.com/quiet>\n",
    )
    new, counts = process_text(page)
    if counts.get("ok-rule3") == 1:
        fail(f"a bold run was treated as a second italic title: {new!r} {counts}")

    # Rule 3 does not fire when the counts differ (leftover: multi-marker).
    page = refs(
        "* Wikipedia, *Silane* and *Tetraethyl orthosilicate* — the "
        "precursors.[^wiki-silane][^wiki-teos][^wiki-nf3]\n",
        "[^wiki-silane]: Wikipedia, *Silane*. <https://en.wikipedia.org/wiki/Silane>\n"
        "[^wiki-teos]: Wikipedia, *Tetraethyl orthosilicate*. "
        "<https://en.wikipedia.org/wiki/Tetraethyl_orthosilicate>\n"
        "[^wiki-nf3]: Wikipedia, *Nitrogen trifluoride*. "
        "<https://en.wikipedia.org/wiki/Nitrogen_trifluoride>\n",
    )
    new, counts = process_text(page)
    if new != page:
        fail(f"a mismatched N-marker/N-italic bullet was changed: {new!r}")
    if counts.get("multi-marker") != 1:
        fail(f"a mismatched N-marker/N-italic bullet was not left as multi-marker: {counts}")

    # Leftover: no " -- " at all.
    page = refs(
        "* Wikipedia, *Silane*.[^wiki-silane]\n",
        "[^wiki-silane]: Wikipedia, *Silane*. <https://en.wikipedia.org/wiki/Silane>\n",
    )
    new, counts = process_text(page)
    if new != page or counts.get("no-dash") != 1:
        fail(f"a dashless bullet was touched: {new!r} {counts}")

    # Leftover: marker with no URL in its own definition.
    page = refs(
        "* Wikipedia, *Silane* — the precursor.[^wiki-silane]\n",
        "[^wiki-silane]: Wikipedia, *Silane* (no URL retrieved).\n",
    )
    new, counts = process_text(page)
    if new != page or counts.get("no-url") != 1:
        fail(f"a urlless-definition bullet was touched: {new!r} {counts}")

    # Never touches the generated index-links block or a bullet outside
    # "## References".
    page = (
        "# T\n\n## Related steps and cross-references\n\n"
        "* Wikipedia, *Foo* — a gloss.[^wiki-foo]\n\n"
        "## References\n\n### Deep dive\n\n"
        "* Wikipedia, *Bar* — a gloss.[^wiki-bar]\n\n"
        "[^wiki-foo]: Wikipedia, *Foo*. <https://en.wikipedia.org/wiki/Foo>\n"
        "[^wiki-bar]: Wikipedia, *Bar*. <https://en.wikipedia.org/wiki/Bar>\n"
    )
    new, counts = process_text(page)
    if "[Wikipedia, *Foo*]" in new:
        fail("a bullet outside '## References' was converted")
    if "[Wikipedia, *Bar*](<https://en.wikipedia.org/wiki/Bar>)" not in new:
        fail("the in-section bullet was not converted")

    # A bullet inside a {dropdown} (an in-force patent note) is left
    # untouched, even though it otherwise matches rule 1.
    page = (
        "# T\n\n## References\n\n### Deep dive\n\n"
        ":::{dropdown} From a patent shown as in force (US 1,234,567; "
        "estimated expiry 2030-01-01) — open to read\n"
        "* Doe (Acme), US 1,234,567 — a gloss.[^pat-doe]\n"
        ":::\n\n"
        "* Wikipedia, *Open* — a gloss.[^wiki-open]\n\n"
        "[^pat-doe]: Doe. <https://patents.google.com/patent/US1234567>\n"
        "[^wiki-open]: Wikipedia, *Open*. <https://en.wikipedia.org/wiki/Open>\n"
    )
    new, counts = process_text(page)
    if counts.get("in-dropdown") != 1:
        fail(f"a dropdown bullet was not recognised: {counts}")
    if "[Doe (Acme), US 1,234,567]" in new:
        fail(f"a bullet inside a dropdown was converted: {new!r}")
    if "[Wikipedia, *Open*](<https://en.wikipedia.org/wiki/Open>)" not in new:
        fail(f"the bullet after the dropdown was not converted: {new!r}")

    # A bullet already converted by hand is left exactly as it is.
    page = refs(
        "* [Wikipedia, *Baz*](<https://en.wikipedia.org/wiki/Baz>) — a "
        "gloss.[^wiki-baz]\n",
        "[^wiki-baz]: Wikipedia, *Baz*. <https://en.wikipedia.org/wiki/Baz>\n",
    )
    new, counts = process_text(page)
    if new != page or counts.get("already-linked") != 1:
        fail(f"an already-linked bullet was not left alone: {new!r} {counts}")

    if problems:
        for p in problems:
            print("FAIL:", p)
        return 1
    print("selftest OK")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="report only, write nothing")
    ap.add_argument("--selftest", action="store_true", help="run offline unit tests")
    ap.add_argument("paths", nargs="*")
    args = ap.parse_args()
    if args.selftest:
        return selftest()
    return run(args.paths, args.check)


if __name__ == "__main__":
    sys.exit(main())
