#!/usr/bin/env python3
"""Generate the "which steps use this" table on machine and material pages.

Report-B B1: every machine and material page answers "which SKY130 steps
use this class" with one paragraph of bare step links — the checked run
``check_machines.py`` and ``check_materials.py`` compare against the
index (see ``docs/plans/readability-guide.md`` R-STEPRUN). This script
adds, directly after that run, a marker-delimited block —
``<!-- step-tables:begin (generated by tools/gen_step_tables.py; do not
edit) -->`` … ``<!-- step-tables:end -->``, the same style as
``gen_index_links.py`` — that turns the run into something a reader can
actually use, without moving or editing the run itself:

* **25 links or fewer:** a ``{table}`` ``Step | Code | Name | Role on
  this page``, one row per link, in the run's own order. ``Step`` is the
  step number, right-aligned; ``Code`` is a fresh ``{ref}`` link (the
  step's code, from ``tools/steps.csv``, as the link text); ``Name`` is
  the step's name, also from ``tools/steps.csv``; ``Role`` comes only
  from the run's own structure — "main" for an unmarked (machine pages)
  or the only (material pages) list, "alternative" for a machine page's
  ``*alternative:*`` list, or the run's own ``*also …:*`` marker text
  (asterisks and the trailing colon stripped) — never invented.
* **More than 25 links:** no table (one would be unusably tall); instead
  a ``{dropdown}`` titled "All N steps (links)" whose body adds nothing
  new, only a one-line pointer to the grouped bullets that already
  follow the run on the same page (the "*also …:*"/tool-grade bullets on
  a machine page, the "steps fall into groups" bullets on a material
  page).

Placement (report-B section 3 item 1; the checked run must stay
byte-identical and in place — R-STEPRUN point 4):

* **Machine pages.** The run is the first non-bullet, step-link-bearing
  block under ``### SKY130 steps assigned to this class``
  (``check_machines.py``'s own selection rule, reused here so the two
  scripts can never disagree about where the run is). The generated
  block goes immediately after it.
* **Material pages.** The run is the paragraph directly after a line
  reading exactly ``Steps:`` (``check_materials.paragraph_after``,
  reused the same way). The generated block goes immediately after it.

``--check`` fails if any page's block is missing, stale (the run
changed) or was hand-edited. Plain ``--selftest`` runs the offline unit
tests below (touches no files). A plain run writes the changed pages and
is idempotent: re-running it with no source change produces no diff.

Run with ``uv run tools/gen_step_tables.py [--check]``.
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
MACHINES = DOCS / "machines"
MATERIALS = DOCS / "materials"
STEPS_CSV = ROOT / "tools" / "steps.csv"

sys.path.insert(0, str(Path(__file__).resolve().parent))
import check_machines  # noqa: E402
import check_materials  # noqa: E402

MARK_BEGIN = "<!-- step-tables:begin (generated by tools/gen_step_tables.py; do not edit) -->"
MARK_END = "<!-- step-tables:end -->"
THRESHOLD = 25

BLOCK_STRIP_RE = re.compile(
    r"\n*" + re.escape(MARK_BEGIN) + r"\n.*?\n" + re.escape(MARK_END) + r"\n*",
    re.S,
)
HEADING_AFTER_RE = re.compile(r"\n#{2,3} ")


# ---------------------------------------------------------------------------
# steps.csv
# ---------------------------------------------------------------------------

def load_steps_csv(path: Path = STEPS_CSV) -> dict[int, tuple[str, str]]:
    """Map a step number to ``(code, name)`` from ``tools/steps.csv``."""
    out: dict[int, tuple[str, str]] = {}
    with path.open(newline="") as f:
        for row in csv.DictReader(f):
            out[int(row["number"])] = (row["code"], row["name"])
    return out


# ---------------------------------------------------------------------------
# Locating the checked run (reuses the checkers' own selection logic)
# ---------------------------------------------------------------------------

def _h3_body_span(text: str, heading: str) -> tuple[int, int]:
    """The (start, end) offsets of the body of the H3 ``heading`` -- from
    just after its own line to the next H2/H3 heading, or the end of the
    page."""
    m = re.search(rf"\n### {re.escape(heading)}\n", text)
    if not m:
        raise ValueError(f"no '### {heading}' heading found")
    body_start = m.end()
    nxt = HEADING_AFTER_RE.search(text, body_start)
    body_end = nxt.start() if nxt else len(text)
    return body_start, body_end


def locate_machine_run(text: str) -> tuple[int, int, str]:
    """(start, end, text) of the checked step-link run on a machine page:
    the first blank-line-separated block under the steps H3 that contains
    a step link and is not a bullet list -- ``check_machines.check()``'s
    own rule, reused so the two scripts can never disagree."""
    body_start, body_end = _h3_body_span(text, check_machines.STEPS_H3)
    body = text[body_start:body_end]
    offset = 0
    for part in body.split("\n\n"):
        if check_machines.STEP_RE.search(part) and not re.match(r"\*\s", part.lstrip()):
            start = body_start + offset
            return start, start + len(part), part
        offset += len(part) + 2
    raise ValueError(f"no step-link run found under '### {check_machines.STEPS_H3}'")


def locate_material_run(text: str) -> tuple[int, int, str]:
    """(start, end, text) of the checked step-link run on a material page:
    the paragraph directly after a line reading exactly "Steps:" --
    ``check_materials.paragraph_after``'s own rule, reused."""
    body_start, body_end = _h3_body_span(text, check_materials.STEPS_H3)
    body = text[body_start:body_end]
    intro = check_materials.STEPS_INTRO
    m = re.search(
        rf"^{re.escape(intro)}[ \t]*\n[ \t]*\n(.+?)(?:\n[ \t]*\n|\Z)",
        body, flags=re.MULTILINE | re.DOTALL,
    )
    if not m:
        raise ValueError(f"no paragraph after a '{intro}' line under '### {check_materials.STEPS_H3}'")
    return body_start + m.start(1), body_start + m.end(1), m.group(1)


# ---------------------------------------------------------------------------
# Extracting (role, step-label) pairs from the run, in the run's own order
# ---------------------------------------------------------------------------

def role_of(marker: str | None) -> str:
    """"main" for no marker; otherwise the marker's own wording, with the
    asterisks and trailing colon stripped ("*alternative:*" -> "alternative";
    "*also for a clean or strip:*" -> "also for a clean or strip")."""
    if marker is None:
        return "main"
    text = marker.strip("*")
    return text[:-1] if text.endswith(":") else text


def machine_run_entries(run: str) -> list[tuple[str, str]]:
    """[(role, step-label)] in the order the run lists them (a machine
    page's run may hold a main list, one "*alternative:*" list and one
    "*also …:*" list; markers may wrap across a line, so whitespace is
    collapsed first, as ``check_machines.step_lists`` already does)."""
    collapsed = re.sub(r"\s+", " ", run)
    parts = check_machines.MARKER_RE.split(collapsed)
    entries = [("main", label) for label in check_machines.STEP_RE.findall(parts[0])]
    for i in range(1, len(parts), 2):
        role = role_of(parts[i])
        entries += [(role, label) for label in check_machines.STEP_RE.findall(parts[i + 1])]
    return entries


def material_run_entries(run: str) -> list[tuple[str, str]]:
    """[(role, step-label)] for a material page's run: always flat, no
    markers, so every entry's role is "main"."""
    collapsed = re.sub(r"\s+", " ", run)
    return [("main", label) for _, label in check_materials.STEP_RE.findall(collapsed)]


# ---------------------------------------------------------------------------
# Rendering the generated block
# ---------------------------------------------------------------------------

def render_table(entries: list[tuple[str, str]], steps_csv: dict[int, tuple[str, str]],
                 caption: str) -> str:
    lines = [
        f":::{{table}} {caption}",
        ":widths: 8 14 46 32",
        "",
        "| Step | Code | Name | Role on this page |",
        "|---:|---|---|---|",
    ]
    for role, label in entries:
        number = int(label.split("-")[1])
        code, name = steps_csv.get(number, ("?", "?"))
        lines.append(f"| {number} | {{ref}}`{code} <{label}>` | {name} | {role} |")
    lines.append(":::")
    return "\n".join(lines)


def render_dropdown(n: int) -> str:
    return "\n".join([
        f":::{{dropdown}} All {n} steps (links)",
        "",
        "See the grouped bullets below for what each step's assignment means.",
        ":::",
    ])


def render_block(entries: list[tuple[str, str]], steps_csv: dict[int, tuple[str, str]],
                 caption: str) -> str:
    if not entries:
        return ""
    if len(entries) <= THRESHOLD:
        return render_table(entries, steps_csv, caption)
    return render_dropdown(len(entries))


def block_text(content: str) -> str:
    return f"{MARK_BEGIN}\n{content}\n{MARK_END}"


# ---------------------------------------------------------------------------
# Splicing into a page
# ---------------------------------------------------------------------------

def strip_existing(text: str) -> str:
    return BLOCK_STRIP_RE.sub("\n\n", text)


def apply_block(text: str, run_end: int, content: str) -> str:
    before = text[:run_end]
    after = text[run_end:].lstrip("\n")
    if content:
        return before + "\n\n" + block_text(content) + "\n\n" + after
    return before + "\n\n" + after


def process_text(text: str, kind: str, steps_csv: dict[int, tuple[str, str]]) -> str:
    """The full new page text for one machine or material page."""
    stripped = strip_existing(text)
    if kind == "machine":
        _, run_end, run = locate_machine_run(stripped)
        entries = machine_run_entries(run)
        caption = check_machines.STEPS_H3
    else:
        _, run_end, run = locate_material_run(stripped)
        entries = material_run_entries(run)
        caption = check_materials.STEPS_H3
    content = render_block(entries, steps_csv, caption)
    return apply_block(stripped, run_end, content)


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

def candidate_pages() -> list[tuple[Path, str]]:
    pages = [(p, "machine") for p in sorted(MACHINES.glob("*.md")) if p.name != "index.md"]
    pages += [(p, "material") for p in sorted(MATERIALS.glob("*.md")) if p.name != "index.md"]
    return pages


def generate() -> dict[Path, str]:
    """{page path: new file text} for every page whose text actually
    changes."""
    steps_csv = load_steps_csv()
    out: dict[Path, str] = {}
    for path, kind in candidate_pages():
        old_text = path.read_text(encoding="utf-8")
        try:
            new_text = process_text(old_text, kind, steps_csv)
        except ValueError as e:
            raise SystemExit(f"{path.relative_to(ROOT)}: {e}")
        if new_text != old_text:
            out[path] = new_text
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="fail if any page's block is missing, stale or hand-edited")
    ap.add_argument("--selftest", action="store_true",
                    help="run the offline self-test and exit; touches no files")
    args = ap.parse_args()

    if args.selftest:
        return selftest()

    changes = generate()
    if args.check:
        if changes:
            for path in sorted(changes):
                print(f"{path.relative_to(ROOT)}: step-tables block missing, stale or hand-edited")
            print(f"{len(changes)} page(s) differ")
            return 1
        print("0 pages differ")
        return 0

    for path, text in changes.items():
        path.write_text(text, encoding="utf-8")
    print(f"{len(changes)} page(s) written")
    return 0


# ---------------------------------------------------------------------------
# Self-test (no repository files touched)
# ---------------------------------------------------------------------------

_STEPS_CSV = {
    1: ("SMAT", "Starting material"),
    2: ("BOX", "Base oxidation"),
    4: ("FOM", "Field oxide mask"),
    7: ("DNM", "Deep N-well mask"),
    13: ("NS19", "Nitride strip"),
}


def _machine_page(run: str) -> str:
    return (
        "(machine-x)=\n# X\n\n"
        "## What the machine class is and how it works\n\ntext\n\n"
        "## Representative 200 mm-era models\n\ntext\n\n"
        "## At SkyWater\n\n"
        "### What SkyWater lists\n\ntext\n\n"
        "### Strength of the evidence\n\ntext\n\n"
        f"### SKY130 steps assigned to this class\n\nIntro line.\n\n{run}\n\n"
        "How the step pages grade the SkyWater tools:\n\n"
        "* **A tool.** Grade text.\n\n"
        "## Consumables and facilities\n\ntext\n"
    )


def _material_page(run: str) -> str:
    return (
        "(material-x)=\n# X\n\n"
        "## At SkyWater\n\n"
        "### What SkyWater's filings and pages list\n\ntext\n\n"
        "### Strength of the evidence\n\ntext\n\n"
        "### SKY130 steps that use this class\n\n"
        "Materials index rows covered:\n\n* `x` — x\n\n"
        f"Steps:\n\n{run}\n\n"
        "The steps fall into groups:\n\n"
        "* **A group.** Text.\n\n"
        "## Supply, handling, safety and facilities\n\ntext\n"
    )


def selftest() -> int:
    problems: list[str] = []

    # 1. Machine page, small run (<=25): a table, placed right after the
    #    run, byte-identical run preserved.
    run = "{ref}`NS19 <step-013>`; *alternative:* {ref}`FOM <step-004>`"
    page = _machine_page(run)
    out = process_text(page, "machine", _STEPS_CSV)
    if run not in out:
        problems.append("machine table case: the run was not preserved byte-identical")
    if MARK_BEGIN not in out or MARK_END not in out:
        problems.append("machine table case: marker block missing")
    if out.index(run) + len(run) > out.index(MARK_BEGIN):
        problems.append("machine table case: generated block is not after the run")
    if "| 13 | {ref}`NS19 <step-013>` | Nitride strip | main |" not in out:
        problems.append(f"machine table case: main row missing/wrong: {out!r}")
    if "| 4 | {ref}`FOM <step-004>` | Field oxide mask | alternative |" not in out:
        problems.append(f"machine table case: alternative row missing/wrong: {out!r}")

    # 2. Machine page, an "*also …:*" marker: role text is the marker's
    #    own wording, asterisks and trailing colon stripped.
    run2 = "{ref}`NS19 <step-013>`; *also for a clean or strip:* {ref}`SMAT <step-001>`"
    out2 = process_text(_machine_page(run2), "machine", _STEPS_CSV)
    if "| 1 | {ref}`SMAT <step-001>` | Starting material | also for a clean or strip |" not in out2:
        problems.append(f"'also' role text wrong: {out2!r}")

    # 3. Material page, small run: table, role always "main".
    mrun = "{ref}`SMAT <step-001>`, {ref}`BOX <step-002>`"
    mout = process_text(_material_page(mrun), "material", _STEPS_CSV)
    if mrun not in mout:
        problems.append("material table case: the run was not preserved byte-identical")
    if "| 1 | {ref}`SMAT <step-001>` | Starting material | main |" not in mout:
        problems.append(f"material table case: row 1 missing/wrong: {mout!r}")
    if "| 2 | {ref}`BOX <step-002>` | Base oxidation | main |" not in mout:
        problems.append(f"material table case: row 2 missing/wrong: {mout!r}")
    # The generated block must directly follow the run, before the
    # "groups" prose (R-STEPRUN placement rule).
    if mout.index(mrun) + len(mrun) > mout.index(MARK_BEGIN) or \
       mout.index(MARK_END) > mout.index("The steps fall into groups"):
        problems.append("material table case: block is not directly after the run")

    # 4. Over the threshold: a dropdown, not a table, and no new links.
    big_run = ", ".join(f"{{ref}}`step-{n:03d} <step-{n:03d}>`" for n in range(1, THRESHOLD + 2))
    big_out = process_text(_material_page(big_run), "material", {
        n: (f"C{n}", f"Name {n}") for n in range(1, THRESHOLD + 2)
    })
    if f"All {THRESHOLD + 1} steps (links)" not in big_out:
        problems.append(f"over-threshold case: dropdown title missing: {big_out!r}")
    if "{table}" in big_out:
        problems.append("over-threshold case: a table was generated instead of a dropdown")
    if "step-001" in big_out.split(MARK_BEGIN, 1)[1]:
        problems.append("over-threshold case: the dropdown body repeats a step link")

    # 5. Idempotent: running twice produces the same text.
    twice = process_text(out, "machine", _STEPS_CSV)
    if twice != out:
        problems.append("re-running on already-generated text is not a no-op")

    # 6. --check-style comparison: generate() reports no page as changed
    #    once its output has been "written" (simulated in memory).
    if process_text(out, "machine", _STEPS_CSV) != out:
        problems.append("generated output is not stable under re-generation")

    # 7. Deterministic: two independent runs on the same input agree.
    if process_text(page, "machine", _STEPS_CSV) != out:
        problems.append("generation is not deterministic")

    if problems:
        for p in problems:
            print("SELFTEST FAIL:", p)
        print(f"{len(problems)} selftest problem(s)")
        return 1
    print("selftest OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
