#!/usr/bin/env python3
"""Generate the "which steps use this" presentation on machine/material pages.

Report-B B1: every machine and material page answers "which SKY130 steps
use this class" with one paragraph of bare step links — the checked run
``check_machines.py`` and ``check_materials.py`` compare against the
index (see ``docs/plans/readability-guide.md`` R-STEPRUN). This script
owns the *whole* presentation of that run: it decides, from the run's own
link count, whether the run is collapsed and what follows it, and writes
everything inside one marker-delimited region —
``<!-- step-tables:begin (generated by tools/gen_step_tables.py; do not
edit) -->`` … ``<!-- step-tables:end -->``, the same style as
``gen_index_links.py``:

* **25 links or fewer.** The run **stays in the open, unchanged** (not
  wrapped in anything), and the generated block goes directly after it: a
  ``{table}`` ``Step | Code | Name`` (plus a ``Role on this page`` column
  only when the run's roles are not all the same — see below), one row
  per link, in the run's own order. ``Step`` is the step number,
  right-aligned; ``Code`` is a fresh ``{ref}`` link (the step's code, from
  ``tools/steps.csv``, as the link text); ``Name`` is the step's name,
  also from ``tools/steps.csv``; ``Role`` comes only from the run's own
  structure — "main" for an unmarked (machine pages) or the only
  (material pages) list, "alternative" for a machine page's
  ``*alternative:*`` list, or the run's own ``*also …:*`` marker text
  (asterisks and the trailing colon stripped) — never invented. When
  every entry's role is the same word, the column is dropped entirely
  (report-B review M2): a reader gains nothing from a column that repeats
  one word N times, and material pages have no markers at all, so
  "main" there is the generator's own filler, not something the page
  says.
* **More than 25 links.** The generator **wraps the run itself** (and, on
  a material page, the ``Steps:`` line with it) in a collapsed
  ``{dropdown}`` titled "All N steps as one line of links (checked
  against the index)" — nothing else: no separate table, no pointer
  sentence, no link the reader has already seen restated. This is the
  *entire* generated block in this case; the run's own bytes, once
  extracted, are copied into the dropdown verbatim.

Placement and the checker contract (report-B section 3 item 1; the
checked run must stay byte-identical — R-STEPRUN point 4):

* **Machine pages.** The run is the first non-bullet, step-link-bearing
  block under ``### SKY130 steps assigned to this class`` — the same
  selection rule ``check_machines.check()`` applies (``locate_machine_run``
  below matches it line for line, so the two scripts cannot silently
  drift apart, though they are two implementations of the same rule, not
  one shared function; see the "Known scope" note below). Wrapping the
  run in a dropdown does not change which block that is: the dropdown's
  opening fence line carries no step link, so it is skipped the same way
  a bullet list is, and the run itself, now the fence's body, is still
  the first non-bullet block that contains one. Verified against the
  real ``check_machines.py`` on all 8 machine pages this branch wraps.
* **Material pages.** The run is the paragraph directly after a line
  reading exactly ``Steps:`` (``check_materials.paragraph_after``'s own
  rule). When wrapped, the ``Steps:`` line and the run go into the
  dropdown *together*, so the run is still the paragraph directly after a
  line reading exactly ``Steps:`` — now the first line of the dropdown's
  body. Verified against the real ``check_materials.py`` on all 10
  material pages this branch wraps.

**Known scope.** ``locate_machine_run``/``locate_material_run`` re-implement
the checkers' own selection regex and paragraph-splitting rather than
calling into ``check_machines.check()``/``check_materials.paragraph_after``
directly (the checkers return problem lists from a whole page, not
offsets into it). They are verified to agree with the checkers on every
page in this repository as of this commit (`--check` plus the checkers
themselves passing on the regenerated result is exactly that proof,
re-run after every change), but "can never disagree" would overstate it;
if a checker's selection rule changes, this file's copy must change with
it.

``--check`` fails if any page's block is missing, stale (the run
changed) or was hand-edited. Plain ``--selftest`` runs the offline unit
tests below (touches no files). A plain run writes the changed pages and
is idempotent: re-running it — including on a page it just wrapped — is
a no-op and never nests a second dropdown inside the first.

Run with ``uv run tools/gen_step_tables.py [--check]``.
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
MACHINES = DOCS / "machines"
MATERIALS = DOCS / "materials"
STEPS_CSV = ROOT / "tools" / "steps.csv"

sys.path.insert(0, str(Path(__file__).resolve().parent))
import check_machines  # noqa: E402
import check_materials  # noqa: E402

MARK_BEGIN = "<!-- step-tables:begin (generated by tools/gen_step_tables.py; do not edit) -->"
MARK_END = "<!-- step-tables:end -->"
THRESHOLD = 25
WRAP_TITLE_RE_FRAGMENT = r"All \d+ steps as one line of links \(checked against the index\)"

BLOCK_STRIP_RE = re.compile(
    r"\n*" + re.escape(MARK_BEGIN) + r"\n.*?\n" + re.escape(MARK_END) + r"\n*",
    re.S,
)
# Matches exactly what render_wrap()/block_text() emit for a > 25-link run:
# the begin marker, the dropdown's opening fence and title, a blank line,
# the wrapped span (captured, byte-identical), the closing fence and the
# end marker. Undoing this (see strip_wrap) restores the page to its
# un-wrapped, "run in the open" form before the run is re-located, so a
# second run of this script is idempotent and never nests one dropdown
# inside another.
WRAP_RE = re.compile(
    re.escape(MARK_BEGIN) + r"\n:::\{dropdown\} " + WRAP_TITLE_RE_FRAGMENT
    + r"\n\n(.*?)\n:::\n" + re.escape(MARK_END),
    re.S,
)
HEADING_AFTER_RE = re.compile(r"\n#{2,3} ")


# ---------------------------------------------------------------------------
# steps.csv
# ---------------------------------------------------------------------------

def load_steps_csv(path: Path = STEPS_CSV) -> dict[int, tuple[str, str]]:
    """Map a step number to ``(code, name)`` from ``tools/steps.csv``."""
    out: dict[int, tuple[str, str]] = {}
    with path.open(newline="") as f:
        for row in csv.DictReader(f):
            out[int(row["number"])] = (row["code"], row["name"])
    return out


# ---------------------------------------------------------------------------
# Locating the checked run (mirrors the checkers' own selection logic)
# ---------------------------------------------------------------------------

def _h3_body_span(text: str, heading: str) -> tuple[int, int]:
    """The (start, end) offsets of the body of the H3 ``heading`` -- from
    just after its own line to the next H2/H3 heading, or the end of the
    page."""
    m = re.search(rf"\n### {re.escape(heading)}\n", text)
    if not m:
        raise ValueError(f"no '### {heading}' heading found")
    body_start = m.end()
    nxt = HEADING_AFTER_RE.search(text, body_start)
    body_end = nxt.start() if nxt else len(text)
    return body_start, body_end


def locate_machine_run(text: str) -> tuple[int, int, str]:
    """(start, end, text) of the checked step-link run on a machine page:
    the first blank-line-separated block under the steps H3 that contains
    a step link and is not a bullet list -- ``check_machines.check()``'s
    own rule. Works whether the run is currently wrapped in a dropdown or
    not: the fence-open/title line carries no step link, so it is treated
    like any other non-matching block and skipped."""
    body_start, body_end = _h3_body_span(text, check_machines.STEPS_H3)
    body = text[body_start:body_end]
    offset = 0
    for part in body.split("\n\n"):
        if check_machines.STEP_RE.search(part) and not re.match(r"\*\s", part.lstrip()):
            start = body_start + offset
            return start, start + len(part), part
        offset += len(part) + 2
    raise ValueError(f"no step-link run found under '### {check_machines.STEPS_H3}'")


def locate_material_run(text: str) -> tuple[int, int, int, str]:
    """(wrap_start, run_start, run_end, text) of the checked step-link run
    on a material page: the paragraph directly after a line reading
    exactly "Steps:" -- ``check_materials.paragraph_after``'s own rule.
    ``wrap_start`` is the start of the "Steps:" line itself: when the run
    is wrapped (> 25 links), the wrap holds "Steps:" and the run together,
    exactly as R-STEPRUN's placement rule for material pages verifies."""
    body_start, body_end = _h3_body_span(text, check_materials.STEPS_H3)
    body = text[body_start:body_end]
    intro = check_materials.STEPS_INTRO
    m = re.search(
        rf"^{re.escape(intro)}[ \t]*\n[ \t]*\n(.+?)(?:\n[ \t]*\n|\Z)",
        body, flags=re.MULTILINE | re.DOTALL,
    )
    if not m:
        raise ValueError(f"no paragraph after a '{intro}' line under '### {check_materials.STEPS_H3}'")
    return body_start + m.start(), body_start + m.start(1), body_start + m.end(1), m.group(1)


# ---------------------------------------------------------------------------
# Extracting (role, step-label) pairs from the run, in the run's own order
# ---------------------------------------------------------------------------

def role_of(marker: str | None) -> str:
    """"main" for no marker; otherwise the marker's own wording, with the
    asterisks and trailing colon stripped ("*alternative:*" -> "alternative";
    "*also for a clean or strip:*" -> "also for a clean or strip")."""
    if marker is None:
        return "main"
    text = marker.strip("*")
    return text[:-1] if text.endswith(":") else text


def machine_run_entries(run: str) -> list[tuple[str, str]]:
    """[(role, step-label)] in the order the run lists them (a machine
    page's run may hold a main list, one "*alternative:*" list and one
    "*also …:*" list; markers may wrap across a line, so whitespace is
    collapsed first, as ``check_machines.step_lists`` already does)."""
    collapsed = re.sub(r"\s+", " ", run)
    parts = check_machines.MARKER_RE.split(collapsed)
    entries = [("main", label) for label in check_machines.STEP_RE.findall(parts[0])]
    for i in range(1, len(parts), 2):
        role = role_of(parts[i])
        entries += [(role, label) for label in check_machines.STEP_RE.findall(parts[i + 1])]
    return entries


def material_run_entries(run: str) -> list[tuple[str, str]]:
    """[(role, step-label)] for a material page's run: always flat, no
    markers, so every entry's role is "main"."""
    collapsed = re.sub(r"\s+", " ", run)
    return [("main", label) for _, label in check_materials.STEP_RE.findall(collapsed)]


# ---------------------------------------------------------------------------
# Rendering the generated content
# ---------------------------------------------------------------------------

def render_table(entries: list[tuple[str, str]], steps_csv: dict[int, tuple[str, str]]) -> str:
    """``Step | Code | Name`` (plus ``Role on this page`` only when the
    roles are not all identical -- review M2: a column that repeats one
    word for every row tells the reader nothing, and "main" on a material
    page is the generator's own filler, not something the page says)."""
    show_role = len({role for role, _ in entries}) > 1
    header = ["Step", "Code", "Name"] + (["Role on this page"] if show_role else [])
    align = ["---:"] + [":---"] * (len(header) - 1)
    n = len(entries)
    caption = f"The {n} step{'s' if n != 1 else ''} above: number, code and name"
    lines = [
        f":::{{table}} {caption}",
        ":widths: 10 16 " + ("58 16" if show_role else "74"),
        "",
        "| " + " | ".join(header) + " |",
        "|" + "|".join(align) + "|",
    ]
    for role, label in entries:
        number = int(label.split("-")[1])
        if number not in steps_csv:
            raise ValueError(f"step {label} is not in tools/steps.csv")
        code, name = steps_csv[number]
        cells = [str(number), f"{{ref}}`{code} <{label}>`", name]
        if show_role:
            cells.append(role)
        lines.append("| " + " | ".join(cells) + " |")
    lines.append(":::")
    return "\n".join(lines)


def wrap_title(n: int) -> str:
    return f"All {n} steps as one line of links (checked against the index)"


def render_wrap(n: int, wrapped_span: str) -> str:
    """The > 25-link case: the run (plus, on material pages, its "Steps:"
    line) collapsed into a dropdown, verbatim -- nothing else (H1)."""
    return f":::{{dropdown}} {wrap_title(n)}\n\n{wrapped_span}\n:::"


def block_text(content: str) -> str:
    return f"{MARK_BEGIN}\n{content}\n{MARK_END}"


# ---------------------------------------------------------------------------
# Splicing into a page
# ---------------------------------------------------------------------------

def strip_wrap(text: str) -> str:
    """Undo a previous > 25-link wrap (H1): replace the whole generated
    wrap -- begin marker, opening fence and title, blank line, wrapped
    span, closing fence, end marker -- with just the captured span,
    restoring the page's un-wrapped, "run in the open" form. This must
    run *before* ``strip_existing``, which knows nothing about a wrapped
    run and would delete it along with the markers."""
    return WRAP_RE.sub(lambda m: m.group(1), text)


def strip_existing(text: str) -> str:
    """Remove a trailing (<= 25-link, table) generated block. Safe to run
    after ``strip_wrap``: by then no wrap-shaped block remains, so this
    can only ever match the table case, which never contains the run."""
    return BLOCK_STRIP_RE.sub("\n\n", text)


def apply_block(text: str, run_end: int, content: str) -> str:
    """<= 25-link case: insert the generated table directly after the
    (untouched) run."""
    before = text[:run_end]
    after = text[run_end:].lstrip("\n")
    if content:
        return before + "\n\n" + block_text(content) + "\n\n" + after
    return before + "\n\n" + after


def apply_wrap(text: str, wrap_start: int, run_end: int, content: str) -> str:
    """> 25-link case: replace the span [wrap_start, run_end) -- the run,
    or on a material page "Steps:" plus the run -- with the generated
    wrap. No padding is needed: the span already sits between the same
    blank lines it always did."""
    return text[:wrap_start] + block_text(content) + text[run_end:]


def process_text(text: str, kind: str, steps_csv: dict[int, tuple[str, str]]) -> str:
    """The full new page text for one machine or material page."""
    stripped = strip_existing(strip_wrap(text))
    if kind == "machine":
        run_start, run_end, run = locate_machine_run(stripped)
        wrap_start = run_start
        entries = machine_run_entries(run)
    else:
        wrap_start, run_start, run_end, run = locate_material_run(stripped)
        entries = material_run_entries(run)
    if not entries:
        raise ValueError("the located run contains no step links")

    if len(entries) <= THRESHOLD:
        content = render_table(entries, steps_csv)
        return apply_block(stripped, run_end, content)

    span = stripped[wrap_start:run_end]
    content = render_wrap(len(entries), span)
    return apply_wrap(stripped, wrap_start, run_end, content)


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

def candidate_pages() -> list[tuple[Path, str]]:
    pages = [(p, "machine") for p in sorted(MACHINES.glob("*.md")) if p.name != "index.md"]
    pages += [(p, "material") for p in sorted(MATERIALS.glob("*.md")) if p.name != "index.md"]
    return pages


def generate() -> dict[Path, str]:
    """{page path: new file text} for every page whose text actually
    changes."""
    steps_csv = load_steps_csv()
    out: dict[Path, str] = {}
    for path, kind in candidate_pages():
        old_text = path.read_text(encoding="utf-8")
        try:
            new_text = process_text(old_text, kind, steps_csv)
        except ValueError as e:
            raise SystemExit(f"{path.relative_to(ROOT)}: {e}")
        if new_text != old_text:
            out[path] = new_text
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="fail if any page's block is missing, stale or hand-edited")
    ap.add_argument("--selftest", action="store_true",
                    help="run the offline self-test and exit; touches no files")
    args = ap.parse_args()

    if args.selftest:
        return selftest()

    changes = generate()
    if args.check:
        if changes:
            for path in sorted(changes):
                print(f"{path.relative_to(ROOT)}: step-tables block missing, stale or hand-edited")
            print(f"{len(changes)} page(s) differ")
            return 1
        print("0 pages differ")
        return 0

    for path, text in changes.items():
        path.write_text(text, encoding="utf-8")
    print(f"{len(changes)} page(s) written")
    return 0


# ---------------------------------------------------------------------------
# Self-test (no repository files touched)
# ---------------------------------------------------------------------------

_STEPS_CSV = {
    1: ("SMAT", "Starting material"),
    2: ("BOX", "Base oxidation"),
    4: ("FOM", "Field oxide mask"),
    7: ("DNM", "Deep N-well mask"),
    13: ("NS19", "Nitride strip"),
}


def _machine_page(run: str) -> str:
    return (
        "(machine-x)=\n# X\n\n"
        "## What the machine class is and how it works\n\ntext\n\n"
        "## Representative 200 mm-era models\n\ntext\n\n"
        "## At SkyWater\n\n"
        "### What SkyWater lists\n\ntext\n\n"
        "### Strength of the evidence\n\ntext\n\n"
        f"### SKY130 steps assigned to this class\n\nIntro line.\n\n{run}\n\n"
        "How the step pages grade the SkyWater tools:\n\n"
        "* **A tool.** Grade text.\n\n"
        "## Consumables and facilities\n\ntext\n"
    )


def _material_page(run: str) -> str:
    return (
        "(material-x)=\n# X\n\n"
        "## At SkyWater\n\n"
        "### What SkyWater's filings and pages list\n\ntext\n\n"
        "### Strength of the evidence\n\ntext\n\n"
        "### SKY130 steps that use this class\n\n"
        "Materials index rows covered:\n\n* `x` — x\n\n"
        f"Steps:\n\n{run}\n\n"
        "The steps fall into groups:\n\n"
        "* **A group.** Text.\n\n"
        "## Supply, handling, safety and facilities\n\ntext\n"
    )


def _big_run(n: int) -> str:
    return ", ".join(f"{{ref}}`step-{i:03d} <step-{i:03d}>`" for i in range(1, n + 1))


def _big_steps_csv(n: int) -> dict[int, tuple[str, str]]:
    return {i: (f"C{i}", f"Name {i}") for i in range(1, n + 1)}


def selftest() -> int:
    problems: list[str] = []

    def check_real_checkers(page_text: str, kind: str, label: str) -> None:
        """Run the *real* check_machines/check_materials logic (not just
        this script's own copy) against a wrapped or unwrapped page, to
        satisfy the coordinator's instruction to verify with the actual
        checkers that a wrapped run still counts as the checked run."""
        if kind == "machine":
            body = check_machines.sections(page_text, "##")
            steps_body = check_machines.sections(body.get("At SkyWater", ""), "###").get(
                check_machines.STEPS_H3, "")
            paragraph = next(
                (p for p in steps_body.split("\n\n")
                 if check_machines.STEP_RE.search(p) and not re.match(r"\*\s", p.lstrip())),
                "",
            )
            if not paragraph:
                problems.append(f"{label}: check_machines found no run paragraph")
        else:
            body = check_materials.sections(page_text, "##")
            steps_body = check_materials.sections(body.get("At SkyWater", ""), "###").get(
                check_materials.STEPS_H3, "")
            paragraph = check_materials.paragraph_after(steps_body, check_materials.STEPS_INTRO)
            if paragraph is None:
                problems.append(f"{label}: check_materials found no paragraph after 'Steps:'")

    # 1. Machine page, small run (<=25): a table, run stays in the open,
    #    unchanged, table directly after it.
    run = "{ref}`NS19 <step-013>`; *alternative:* {ref}`FOM <step-004>`"
    page = _machine_page(run)
    out = process_text(page, "machine", _STEPS_CSV)
    if run not in out:
        problems.append("machine table case: the run was not preserved byte-identical")
    if ":::{dropdown}" in out:
        problems.append("machine table case: a <=25-link run must not be wrapped")
    if MARK_BEGIN not in out or MARK_END not in out:
        problems.append("machine table case: marker block missing")
    if out.index(run) + len(run) > out.index(MARK_BEGIN):
        problems.append("machine table case: generated block is not after the run")
    if "| 13 | {ref}`NS19 <step-013>` | Nitride strip | main |" not in out:
        problems.append(f"machine table case: main row missing/wrong: {out!r}")
    if "| 4 | {ref}`FOM <step-004>` | Field oxide mask | alternative |" not in out:
        problems.append(f"machine table case: alternative row missing/wrong: {out!r}")
    check_real_checkers(out, "machine", "machine table case")

    # 1b. M2: when every role is the same word, the Role column is
    #     dropped entirely (both the header and every data row).
    uniform_run = "{ref}`NS19 <step-013>`, {ref}`FOM <step-004>`"
    uniform_out = process_text(_machine_page(uniform_run), "machine", _STEPS_CSV)
    if "Role on this page" in uniform_out:
        problems.append(f"uniform-role case: Role column was not dropped: {uniform_out!r}")
    if "| 13 | {ref}`NS19 <step-013>` | Nitride strip |" not in uniform_out:
        problems.append(f"uniform-role case: row missing/wrong: {uniform_out!r}")

    # 2. Machine page, an "*also …:*" marker: role text is the marker's
    #    own wording, asterisks and trailing colon stripped (and the
    #    column is kept, since roles now differ).
    run2 = "{ref}`NS19 <step-013>`; *also for a clean or strip:* {ref}`SMAT <step-001>`"
    out2 = process_text(_machine_page(run2), "machine", _STEPS_CSV)
    if "| 1 | {ref}`SMAT <step-001>` | Starting material | also for a clean or strip |" not in out2:
        problems.append(f"'also' role text wrong: {out2!r}")

    # 3. Material page, small run: table, role column dropped (material
    #    pages have no markers, so every role is always "main").
    mrun = "{ref}`SMAT <step-001>`, {ref}`BOX <step-002>`"
    mout = process_text(_material_page(mrun), "material", _STEPS_CSV)
    if mrun not in mout:
        problems.append("material table case: the run was not preserved byte-identical")
    if "Role on this page" in mout:
        problems.append(f"material table case: Role column was not dropped: {mout!r}")
    if "| 1 | {ref}`SMAT <step-001>` | Starting material |" not in mout:
        problems.append(f"material table case: row 1 missing/wrong: {mout!r}")
    if "| 2 | {ref}`BOX <step-002>` | Base oxidation |" not in mout:
        problems.append(f"material table case: row 2 missing/wrong: {mout!r}")
    # The generated block must directly follow the run, before the
    # "groups" prose (R-STEPRUN placement rule).
    if mout.index(mrun) + len(mrun) > mout.index(MARK_BEGIN) or \
       mout.index(MARK_END) > mout.index("The steps fall into groups"):
        problems.append("material table case: block is not directly after the run")
    check_real_checkers(mout, "material", "material table case")

    # 4. Over the threshold, machine page: the run itself is wrapped in a
    #    dropdown (H1) -- no separate table, no pointer sentence, no link
    #    repeated outside the dropdown.
    n = THRESHOLD + 1
    big_run = _big_run(n)
    big_csv = _big_steps_csv(n)
    big_page = _machine_page(big_run)
    big_out = process_text(big_page, "machine", big_csv)
    if wrap_title(n) not in big_out:
        problems.append(f"over-threshold machine case: dropdown title missing: {big_out!r}")
    if "{table}" in big_out:
        problems.append("over-threshold machine case: a table was generated as well as the dropdown")
    if big_run not in big_out:
        problems.append("over-threshold machine case: the run was not preserved byte-identical")
    # Exactly one occurrence of the run's first link: nothing repeats it
    # outside the dropdown (no pointer sentence, no table).
    if big_out.count("{ref}`step-001 <step-001>`") != 1:
        problems.append("over-threshold machine case: a link is repeated outside the dropdown")
    # The dropdown must be *inside* the markers, and the intro sentence
    # must stay outside (in the open) before it.
    if not (big_out.index(MARK_BEGIN) < big_out.index(":::{dropdown}") < big_out.index(big_run)
            < big_out.index(MARK_END)):
        problems.append(f"over-threshold machine case: wrap is not inside the markers: {big_out!r}")
    if big_out.index("Intro line.") > big_out.index(MARK_BEGIN):
        problems.append("over-threshold machine case: the intro sentence is not in the open, before the wrap")
    check_real_checkers(big_out, "machine", "over-threshold machine case")

    # 4b. Over the threshold, material page: "Steps:" and the run are
    #     wrapped together (R-STEPRUN's material-page placement rule).
    big_mout = process_text(_material_page(big_run), "material", big_csv)
    if "Steps:\n\n" + big_run not in big_mout:
        problems.append(f"over-threshold material case: 'Steps:' and the run are not wrapped together: {big_mout!r}")
    if big_mout.index(MARK_END) > big_mout.index("The steps fall into groups"):
        problems.append("over-threshold material case: wrap is not directly before the grouped bullets")
    check_real_checkers(big_mout, "material", "over-threshold material case")

    # 5. Idempotent and non-nesting: re-running on already-wrapped output
    #    (and on already-tabled output) is a no-op, and no second dropdown
    #    appears inside the first.
    for label, first_out, kind, csv_ in (
        ("table", out, "machine", _STEPS_CSV),
        ("wrap", big_out, "machine", big_csv),
        ("material wrap", big_mout, "material", big_csv),
    ):
        second = process_text(first_out, kind, csv_)
        if second != first_out:
            problems.append(f"{label} case: re-running on already-generated text is not a no-op")
        if first_out.count(":::{dropdown}") > 1:
            problems.append(f"{label} case: more than one dropdown present after one generation")
        if second.count(":::{dropdown}") != first_out.count(":::{dropdown}"):
            problems.append(f"{label} case: re-running changed the number of dropdowns (nesting?)")

    # 6. Deterministic: two independent runs on the same fresh input agree.
    if process_text(page, "machine", _STEPS_CSV) != out:
        problems.append("generation is not deterministic (table case)")
    if process_text(big_page, "machine", big_csv) != big_out:
        problems.append("generation is not deterministic (wrap case)")

    # 7. --check semantics: a hand-edit to a wrapped dropdown's title is
    #    caught (the run inside is still found, but the wrap no longer
    #    matches WRAP_RE, so it is not silently treated as canonical).
    tampered = big_out.replace(wrap_title(n), "All 999 steps as one line of links (checked against the index)")
    retampered = process_text(tampered, "machine", big_csv)
    if retampered == tampered:
        problems.append("a hand-edited wrap title was not corrected by regeneration")
    if retampered != big_out:
        problems.append("regenerating a hand-edited wrap does not converge back to the canonical form")

    # 8. Missing steps.csv entry and an empty run both raise, rather than
    #    silently emitting "?" or an empty block (L3).
    try:
        process_text(page, "machine", {})
        problems.append("a step missing from steps.csv did not raise")
    except ValueError:
        pass
    try:
        process_text(_machine_page("*alternative:*"), "machine", _STEPS_CSV)
        problems.append("a run with no step links did not raise")
    except ValueError:
        pass

    # 9. --check semantics (review L6: nothing exercised this before):
    #    generate() -- what --check compares -- reports every page that
    #    needs writing, reports none once they are written, and reports a
    #    page again the moment its run changes underneath it.
    global MACHINES, MATERIALS
    orig_machines, orig_materials = MACHINES, MATERIALS
    with __import__("tempfile").TemporaryDirectory() as tmp:
        tmp_machines = Path(tmp) / "machines"
        tmp_materials = Path(tmp) / "materials"
        tmp_machines.mkdir()
        tmp_materials.mkdir()
        machine_path = tmp_machines / "x.md"
        material_path = tmp_materials / "y.md"
        machine_path.write_text(page)
        material_path.write_text(_material_page(mrun))
        MACHINES, MATERIALS = tmp_machines, tmp_materials
        try:
            changes = generate()
            if set(changes) != {machine_path, material_path}:
                problems.append(f"--check baseline: unexpected changed set {sorted(changes)}")
            for p, text in changes.items():
                p.write_text(text, encoding="utf-8")
            if generate():
                problems.append("--check semantics: pages still differ right after being written")
            machine_path.write_text(page.replace("{ref}`FOM <step-004>`", ""))
            changed_again = generate()
            if machine_path not in changed_again:
                problems.append("--check semantics: a source change to the run was not detected")
        finally:
            MACHINES, MATERIALS = orig_machines, orig_materials

    if problems:
        for p in problems:
            print("SELFTEST FAIL:", p)
        print(f"{len(problems)} selftest problem(s)")
        return 1
    print("selftest OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
