#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml>=6"]
# ///
"""Rewrite the generated "related index entries" block on process pages.

Every step, category, machine, material and mask page, and the two
overview pages, gets ONE generated block — delimited by
``<!-- index-links:begin -->`` / ``<!-- index-links:end -->`` — linking
it to the patent, paper and filings index entries that concern it, so a
reader of the process page can find them without visiting the indexes
first. See ``docs/plans/progress-topic-index-links.md`` for the design.

A page qualifies when its docs label (any ``(label)=`` anchor on it) is:

* a ``relevance.target`` in ``data/patents.yaml``,
* a ``related_docs.label`` in ``data/papers.yaml``, or
* a ``related_docs.label`` in ``data/filings.yaml``,

and that label resolves to a file outside ``docs/references/`` and
``docs/plans/`` (a label resolving into the generated index pages
themselves is out of scope for this direction; those pages already link
back to process pages on their own).

Block content, per dataset, heading-less (bold inline lead-ins only):

* **Related patents.** Expired families listed as ``{ref}`` links
  (number, title, year). Families still in force or of unknown status
  go inside one collapsed ``{dropdown}`` whose title names only the
  count, plus a one-sentence estimate/not-legal-advice caveat.
* **Related papers.** ``{ref}`` links, reusing ``gen_papers.line()``.
* **Related filings.** ``{ref}`` links, reusing ``gen_filings.short_line()``.

A page with more than ``THRESHOLD`` entries in one category shows the
count and a link to that dataset's grouped page instead of listing them
(the "in force is hidden" rule is then trivially satisfied: no numbers
are shown on the process page at all).

The block is inserted immediately before the page's ``## References``
heading, which every target page has exactly once. ``--check`` fails if
any page's block is missing, stale or was hand-edited (i.e. differs from
what this script would write). ``--selftest`` exercises the block-
building and text-splicing logic on synthetic data, touching nothing in
the repository.

Run with ``uv run tools/gen_index_links.py [--check]``.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
PATENTS_DATA = ROOT / "data" / "patents.yaml"
PAPERS_DATA = ROOT / "data" / "papers.yaml"
FILINGS_DATA = ROOT / "data" / "filings.yaml"

sys.path.insert(0, str(ROOT / "tools"))
import check_patents  # noqa: E402
import gen_patents  # noqa: E402
import gen_papers  # noqa: E402
import gen_filings  # noqa: E402

MARK_BEGIN = "<!-- index-links:begin (generated by tools/gen_index_links.py; do not edit) -->"
MARK_END = "<!-- index-links:end -->"
REF_HEADING = "## References"
THRESHOLD = 12

BLOCK_STRIP_RE = re.compile(
    r"\n*" + re.escape(MARK_BEGIN) + r"\n.*?\n" + re.escape(MARK_END) + r"\n*",
    re.S,
)


# ---------------------------------------------------------------------------
# Loading and label resolution
# ---------------------------------------------------------------------------

def load_families() -> list[dict]:
    data = yaml.load(PATENTS_DATA.read_text(encoding="utf-8"), Loader=check_patents.Loader)
    fams = data["families"]
    return sorted(fams, key=lambda f: (str(f["dates"]["priority"]), f["representative"]))


def load_papers() -> list[dict]:
    papers = yaml.safe_load(PAPERS_DATA.read_text(encoding="utf-8"))
    return sorted(papers, key=lambda p: p["label"])


def load_filings() -> list[dict]:
    data = yaml.safe_load(FILINGS_DATA.read_text(encoding="utf-8"))
    return data["filings"]


def in_scope(path: Path) -> bool:
    """True for a process page (outside the generated reference indexes
    and the plans directory, which ``doc_labels()`` already excludes)."""
    rel = path.relative_to(DOCS).as_posix()
    return not rel.startswith("references/")


def build_targets(labels: dict[str, Path], fams: list[dict], papers: list[dict],
                   filings: list[dict]) -> dict[Path, dict[str, list]]:
    """Map each in-scope page path to the families/papers/filings that name
    one of its labels, in the datasets' own stable order, deduplicated by
    id (a page can carry several labels; an item naming more than one of
    them is listed once)."""
    pages: dict[Path, dict[str, list]] = {}

    def bucket(path: Path) -> dict[str, list]:
        return pages.setdefault(path, {"patents": [], "papers": [], "filings": []})

    seen_fam: dict[Path, set[str]] = {}
    for f in fams:
        targets = {r["target"] for r in f.get("relevance", [])}
        for t in targets:
            path = labels.get(t)
            if path is None or not in_scope(path):
                continue
            done = seen_fam.setdefault(path, set())
            if f["id"] in done:
                continue
            done.add(f["id"])
            bucket(path)["patents"].append(f)

    seen_paper: dict[Path, set[str]] = {}
    for p in papers:
        for r in p.get("related_docs") or []:
            path = labels.get(r["label"])
            if path is None or not in_scope(path):
                continue
            done = seen_paper.setdefault(path, set())
            if p["id"] in done:
                continue
            done.add(p["id"])
            bucket(path)["papers"].append(p)

    seen_filing: dict[Path, set[str]] = {}
    for f in filings:
        for r in f.get("related_docs") or []:
            path = labels.get(r["label"])
            if path is None or not in_scope(path):
                continue
            done = seen_filing.setdefault(path, set())
            if f["id"] in done:
                continue
            done.add(f["id"])
            bucket(path)["filings"].append(f)

    return pages


# ---------------------------------------------------------------------------
# Block rendering
# ---------------------------------------------------------------------------

STATUS_ORDER = ["in force", "unknown", "expired"]


def status_breakdown(fams: list[dict]) -> str:
    from collections import Counter
    c = Counter(gen_patents.status_word(f) for f in fams)
    return ", ".join(f"{c[s]} {s}" for s in STATUS_ORDER if c[s])


def expired_line(fam: dict) -> str:
    label = gen_patents.label_of(fam)
    pn = gen_patents.display_pn(gen_patents.rep_member(fam))
    year = str(fam["dates"]["priority"])[:4]
    return f"* {{ref}}`{pn} <{label}>` — {gen_patents.esc(fam['title'])} ({year})"


def render_patents(fams: list[dict]) -> list[str]:
    if not fams:
        return []
    if len(fams) > THRESHOLD:
        return [
            f"**Related patents.** {gen_patents.plural(len(fams), 'family')} concern this page "
            f"({status_breakdown(fams)}); see {{ref}}`patents-by-module` for the full, grouped list "
            "(families still in force or of unknown status are collapsed there too)."
        ]
    expired = [f for f in fams if f["expired"] is True]
    collapsed = [f for f in fams if f["expired"] is not True]
    lines = ["**Related patents.**", ""]
    for f in expired:
        lines.append(expired_line(f))
    if collapsed:
        if expired:
            lines.append("")
        lines.append(f":::{{dropdown}} {gen_patents.plural(len(collapsed), 'family')} in force or status unknown")
        lines.append("")
        lines.append("Status and expiry are estimates from public records and are not legal advice.")
        lines.append("")
        for f in collapsed:
            lines.append(gen_patents.family_link_line(f))
        lines.append(":::")
    return lines


def render_papers(papers: list[dict]) -> list[str]:
    if not papers:
        return []
    if len(papers) > THRESHOLD:
        return [
            f"**Related papers.** {gen_papers.plural(len(papers))} relate to this page; see "
            "{ref}`papers-by-module` for the full, grouped list."
        ]
    lines = ["**Related papers.**", ""]
    for p in papers:
        lines.append(gen_papers.line(p))
    return lines


def render_filings(filings: list[dict]) -> list[str]:
    if not filings:
        return []
    if len(filings) > THRESHOLD:
        return [
            f"**Related filings.** {gen_filings.plural(len(filings), 'filing')} relate to this page; see "
            "{ref}`filings-by-relationship` for the full, grouped list."
        ]
    lines = ["**Related filings.**", ""]
    for f in filings:
        lines.append(gen_filings.short_line(f))
    return lines


def render_block(data: dict[str, list]) -> str:
    parts = [p for p in (render_patents(data["patents"]), render_papers(data["papers"]),
                          render_filings(data["filings"])) if p]
    if not parts:
        return ""
    lines: list[str] = []
    for i, part in enumerate(parts):
        if i:
            lines.append("")
        lines.extend(part)
    return "\n".join(lines)


def block_text(content: str) -> str:
    return f"{MARK_BEGIN}\n{content}\n{MARK_END}"


# ---------------------------------------------------------------------------
# Splicing into a page
# ---------------------------------------------------------------------------

def strip_existing(text: str) -> str:
    """Remove an existing generated block (and the blank lines around it),
    collapsing to a single blank line, wherever it is in the file."""
    return BLOCK_STRIP_RE.sub("\n\n", text)


def apply_block(text: str, content: str, where: str) -> str:
    text = strip_existing(text)
    marker = f"\n{REF_HEADING}\n"
    idx = text.find(marker)
    if idx == -1:
        raise SystemExit(f"{where}: no '{REF_HEADING}' heading found")
    if text.find(marker, idx + 1) != -1:
        raise SystemExit(f"{where}: more than one '{REF_HEADING}' heading found")
    before = text[:idx].rstrip("\n")
    after_heading = text[idx + 1:]
    if content:
        return before + "\n\n" + block_text(content) + "\n\n" + after_heading
    return before + "\n\n" + after_heading


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

def candidate_pages(labels: dict[str, Path], targets: dict[Path, dict[str, list]]) -> set[Path]:
    """Every page that should have a block, plus every page that currently
    has one (so a block can be removed when a page no longer qualifies)."""
    pages = set(targets)
    for path in DOCS.rglob("*.md"):
        rel = path.relative_to(DOCS).as_posix()
        if rel.startswith("plans/") or rel.startswith("_build/") or not in_scope(path):
            continue
        if MARK_BEGIN in path.read_text(encoding="utf-8"):
            pages.add(path)
    return pages


def generate() -> dict[Path, str]:
    """Return {page path: new file text} for every page that should be
    written (i.e. whose text actually changes)."""
    labels = check_patents.doc_labels()
    fams = load_families()
    papers = load_papers()
    filings = load_filings()
    targets = build_targets(labels, fams, papers, filings)
    empty: dict[str, list] = {"patents": [], "papers": [], "filings": []}
    out: dict[Path, str] = {}
    for path in sorted(candidate_pages(labels, targets)):
        data = targets.get(path, empty)
        content = render_block(data)
        old_text = path.read_text(encoding="utf-8")
        new_text = apply_block(old_text, content, str(path.relative_to(ROOT)))
        if new_text != old_text:
            out[path] = new_text
    return out


def summary(labels: dict[str, Path], fams: list[dict], papers: list[dict], filings: list[dict],
            targets: dict[Path, dict[str, list]]) -> str:
    n_steps = sum(1 for p in targets if p.relative_to(DOCS).parts[0] == "steps")
    n_machines = sum(1 for p in targets if p.relative_to(DOCS).parts[0] == "machines")
    n_materials = sum(1 for p in targets if p.relative_to(DOCS).parts[0] == "materials")
    n_categories = sum(1 for p in targets if p.relative_to(DOCS).parts[0] == "categories")
    n_masks = sum(1 for p in targets if p.relative_to(DOCS).parts[0] == "masks")
    n_overview = sum(1 for p in targets if p.relative_to(DOCS).parts[0] == "overview")
    all_fams = {f["id"] for d in targets.values() for f in d["patents"]}
    all_papers = {p["id"] for d in targets.values() for p in d["papers"]}
    all_filings = {f["id"] for d in targets.values() for f in d["filings"]}
    return (f"{len(targets)} pages linked (steps {n_steps}, machines {n_machines}, "
            f"materials {n_materials}, categories {n_categories}, masks {n_masks}, "
            f"overview {n_overview}); {len(all_fams)} patent families, {len(all_papers)} papers, "
            f"{len(all_filings)} filings referenced")


def stale_pages_in(dir_name: str) -> list[str]:
    """One problem string per page under ``docs/<dir_name>/`` whose
    generated index-links block is missing, stale or was hand-edited.

    Shared by ``check_steps.py``, ``check_machines.py``,
    ``check_materials.py`` and ``check_masks.py`` (progress file item 8)
    so the diff logic that decides "stale or hand-edited" lives in one
    place instead of four copies of it."""
    changes = generate()
    prefix = f"{dir_name}/"
    problems = []
    for p in sorted(changes):
        rel = p.relative_to(DOCS).as_posix()
        if rel.startswith(prefix):
            problems.append(
                f"{p.relative_to(ROOT)}: index-links block missing, stale or hand-edited "
                "(run `uv run tools/gen_index_links.py`)"
            )
    return problems


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="fail if any page's block is missing, stale or hand-edited")
    ap.add_argument("--selftest", action="store_true", help="run the offline self-test and exit; touches no files")
    args = ap.parse_args()

    if args.selftest:
        return selftest()

    labels = check_patents.doc_labels()
    fams = load_families()
    papers = load_papers()
    filings = load_filings()
    targets = build_targets(labels, fams, papers, filings)
    changes = generate()

    if args.check:
        if changes:
            for path in sorted(changes):
                print(f"{path.relative_to(ROOT)}: block missing, stale or hand-edited")
            print(f"{len(changes)} page(s) differ. {summary(labels, fams, papers, filings, targets)}")
            return 1
        print(f"0 pages differ. {summary(labels, fams, papers, filings, targets)}")
        return 0

    for path, text in changes.items():
        path.write_text(text, encoding="utf-8")
    verb_count = len(changes)
    print(f"{verb_count} page(s) written. {summary(labels, fams, papers, filings, targets)}")
    return 0


# ---------------------------------------------------------------------------
# Self-test (no repository files touched)
# ---------------------------------------------------------------------------

def _fam(id_, expired, priority="2005-01-01", pn="US10000000B2", title="A widget", status="Active"):
    return {
        "id": id_,
        "representative": pn,
        "title": title,
        "dates": {"priority": priority, "filing": priority, "grant": priority},
        "legal_status": {"status": status, "source": "test"},
        "expiry": {"date": "2025-01-01", "estimated": True, "basis": "test"},
        "expired": expired,
        "members": [{"number": pn, "country": "US", "kind": "B2",
                     "links": {"espacenet": "https://x", "google_patents": "https://y"}}],
        "relevance": [{"target": "step-999", "relation": "cited-on-page", "reason": "Test reason."}],
    }


def _paper(id_, label):
    return {"id": id_, "label": label, "authors": ["Smith, A."], "venue_series": "TED", "year": 2020,
            "title_display": "A test paper", "free_full_text": [], "basis": "named-process"}


def _filing(id_):
    return {"id": id_, "company": "Test Co.", "form": "10-K", "filed": "2020-01-01", "title": "Annual report"}


def selftest() -> int:
    problems = []

    # 1. Splicing: insertion before "## References", exactly one blank line
    #    on each side, and idempotent on a no-op re-apply.
    page = "# Title\n\nSome text.\n\n## References\n\n### Cross-check\n"
    once = apply_block(page, "**Related patents.**\n* a link", "test")
    expect = ("# Title\n\nSome text.\n\n" + block_text("**Related patents.**\n* a link") +
              "\n\n## References\n\n### Cross-check\n")
    if once != expect:
        problems.append(f"splice mismatch:\n{once!r}\nexpected:\n{expect!r}")
    twice = apply_block(once, "**Related patents.**\n* a link", "test")
    if twice != once:
        problems.append("re-applying the same content is not a no-op")

    # 2. Removing a block when the page no longer qualifies.
    removed = apply_block(once, "", "test")
    if removed != "# Title\n\nSome text.\n\n## References\n\n### Cross-check\n":
        problems.append(f"block removal left residue:\n{removed!r}")

    # 3. Threshold: <=12 lists everything, >12 collapses to a count + link.
    fams13 = [_fam(f"GP{i}", True) for i in range(13)]
    block13 = render_patents(fams13)
    if not any("patents-by-module" in l for l in block13):
        problems.append("13 families did not collapse to a by-module link")
    if any("patent-gp" in l for l in block13):
        problems.append("13-family collapsed block still names a family")
    fams12 = [_fam(f"GP{i}", True) for i in range(12)]
    block12 = render_patents(fams12)
    if not all(f"patent-gp{i}" in "\n".join(block12) for i in range(12)):
        problems.append("12 families did not all appear in the list form")

    # 4. Expired vs. collapsed split and dropdown wording.
    mixed = [_fam("GP1", True), _fam("GP2", False), _fam("GP3", "unknown")]
    block = "\n".join(render_patents(mixed))
    if "patent-gp1" not in block or ":::{dropdown}" not in block:
        problems.append("mixed expired/collapsed rendering missing a part")
    if "2 families in force or status unknown" not in block:
        problems.append("dropdown title wording wrong")
    if "patent-gp2" not in block or "patent-gp3" not in block:
        problems.append("collapsed families not linked inside the dropdown")
    if "not legal advice" not in block:
        problems.append("collapsed dropdown missing the estimate/not-legal-advice sentence")

    # 5. Papers and filings render at all, and also collapse over threshold.
    p_block = render_papers([_paper("doi:1", "paper-x-2020a")])
    if not any("paper-x-2020a" in l for l in p_block):
        problems.append("paper line missing")
    p_over = render_papers([_paper(f"doi:{i}", f"paper-x-2020{chr(97+i)}") for i in range(13)])
    if not any("papers-by-module" in l for l in p_over):
        problems.append("13 papers did not collapse to a by-module link")
    f_block = render_filings([_filing("f-1")])
    if not any("f-1" in l for l in f_block):
        problems.append("filing line missing")
    f_over = render_filings([_filing(f"f-{i}") for i in range(13)])
    if not any("filings-by-relationship" in l for l in f_over):
        problems.append("13 filings did not collapse to a by-relationship link")

    # 6. Empty input renders nothing.
    if render_block({"patents": [], "papers": [], "filings": []}) != "":
        problems.append("empty data did not render an empty block")

    if problems:
        for p in problems:
            print("SELFTEST FAIL:", p)
        print(f"{len(problems)} selftest problem(s)")
        return 1
    print("selftest OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
