#!/usr/bin/env python3
"""Link a source's own italic title where prose names it and cites it (C4 row 2, W0c).

docs/plans/readability/report-C.md finding C4, second row of the table:

    A source *named* in prose by its italic title, with that source's marker
    in the same sentence ("the PDK's *Periphery rules* page …[^pdk-periph]")
    -> Link the italic title to the definition's first URL, first occurrence
       per H2 only; marker stays.

docs/plans/readability-guide.md R-LINKS step 5 restates this. Unlike C1 (the
three reading lists), this rule works on ordinary prose, so it needs its own
safety rules, applied per block before any sentence is examined:

* only the body of the page (before "## References" -- the reading lists are
  C1's territory, handled by tools/fix_reading_list_links.py);
* never inside a quotation (quoted spans are masked out before matching, so
  neither a title nor a sentence boundary is ever found inside one);
* never in a heading line;
* never in any table line (this script treats a whole table -- header row
  and data rows alike -- as off limits, which is stricter than the letter
  of C4's "never inside ... tables' header rows": a table cell rarely holds
  a full sentence, and mixing this rule's sentence logic with cell/column
  boundaries is not worth the risk at this scale);
* never inside a {dropdown} (an in-force patent note keeps its own text
  untouched, exactly as tools/fix_reading_list_links.py's rule for bullets).

For each footnote label defined on the page whose definition's own first
``*italic*`` span gives it a title: find every "sentence" (a punctuation
heuristic, like the rest of this project's tooling -- see
docs/plans/agent-briefs.md's note on ``number_order``) in the eligible body
text that contains both `[^label]` and an exact, not-already-linked
``*title*`` span. Link the *first* such span, per (H2, title) pair, to the
label's own definition's first URL; every later occurrence of the same
title in the same H2 is left alone. The marker is never touched.

Idempotent: a ``*title*`` immediately preceded by "[" and followed by "](<"
is recognised as already linked and never re-processed.

Usage::

    uv run tools/link_named_titles.py [--check] [path ...]
    uv run tools/link_named_titles.py --selftest
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"

sys.path.insert(0, str(Path(__file__).resolve().parent))
import check_inforce  # noqa: E402  (for its {dropdown} fence parser)

DEF_RE = re.compile(
    r"^\[\^([A-Za-z0-9_-]+)\]:(.*?)(?=^\[\^[A-Za-z0-9_-]+\]:|\Z)", re.M | re.S
)
FIRST_DEF_RE = re.compile(r"^\[\^[A-Za-z0-9][A-Za-z0-9_-]*\]:", re.M)
MARK_RE = re.compile(r"\[\^([A-Za-z0-9_-]+)\]")
URL_RE = re.compile(r"<(https?://[^<>\s]+)>")
TITLE_IN_DEF_RE = re.compile(r"\*([^*\n]+)\*")
# A single-asterisk italic span: never a run of "**bold**" (an opening or
# closing "*" adjacent to another "*"), and never a list bullet's own
# leading "* " (CommonMark forbids whitespace directly inside an emphasis
# delimiter, so "*" followed or preceded by whitespace is never emphasis --
# this also keeps "* The PDK's *Periphery rules* page ..." from matching
# from the bullet's own marker instead of the real title's opening "*").
ITALIC_RE = re.compile(r"(?<!\*)\*(?![\s*])([^*]+?)(?<![\s*])\*(?!\*)")
QUOTE_RE = re.compile(r'"[^"\n]*"|“[^”\n]*”')
H2_RE = re.compile(r"^## (.+?)\s*$", re.M)
# A sentence boundary: end punctuation, then any markers immediately glued
# to it (the house style puts the marker right after the full stop), then
# whitespace, before the next sentence's first character.
SENT_SPLIT_RE = re.compile(
    r'(?<=[.?!])(?:\[\^[A-Za-z0-9_-]+\])*\s+(?=[A-Z0-9"“*`{(])'
)
GENBLOCK_RE = re.compile(
    r"<!-- index-links:begin \(generated by tools/gen_index_links\.py; "
    r"do not edit\) -->.*?<!-- index-links:end -->",
    re.S,
)


def page_titles(text: str) -> dict[str, tuple[str, str]]:
    """``{label: (title, first URL)}`` from the page's own definitions.

    ``title`` is the first ``*italic*`` span written inside that label's own
    ``[^label]:`` definition (citation-style.md rule 3: title is always
    italicised there). A label with no italic title, or no URL, is omitted:
    there is nothing for this rule to match or link.
    """
    out: dict[str, tuple[str, str]] = {}
    for lab, body in DEF_RE.findall(text):
        tm = TITLE_IN_DEF_RE.search(body)
        um = URL_RE.findall(body)
        if tm and um:
            out[lab] = (tm.group(1), um[0])
    return out


REFERENCES_RE = re.compile(r"^## References\s*$", re.M)


def split_body(text: str) -> tuple[str, int]:
    """Prose body: before "## References" (C1's reading lists) and before
    the first footnote definition (belt and suspenders -- References
    always precedes the definitions in this house style, but stop at
    whichever comes first). Returns the body text and its line count.
    """
    ends = [m.start() for m in (REFERENCES_RE.search(text), FIRST_DEF_RE.search(text)) if m]
    body = text[: min(ends)] if ends else text
    return body, body.count("\n")


def mask_quotes(s: str) -> str:
    return QUOTE_RE.sub(lambda m: " " * len(m.group(0)), s)


def is_table_line(line: str) -> bool:
    return line.lstrip().startswith("|")


def is_heading_line(line: str) -> bool:
    return line.lstrip().startswith("#")


def is_blockquote_line(line: str) -> bool:
    return line.lstrip().startswith(">")


def already_linked(text: str, start: int, end: int) -> bool:
    return text[max(0, start - 1) : start] == "[" and text[end : end + 3] == "](<"


def process_text(text: str) -> tuple[str, dict[str, int]]:
    """Link named titles in the page's body prose. Returns (new_text, counts).

    ``counts`` has one key per label that was linked (value: 1) plus
    ``"linked"`` (the total) -- kept small since the interesting number is
    the total and the per-page list, not a taxonomy like C1's.
    """
    counts: dict[str, int] = {"linked": 0}
    titles = page_titles(text)
    if not titles:
        return text, counts
    body, _ = split_body(text)
    genblock_lines: set[int] = set()
    gm = GENBLOCK_RE.search(body)
    if gm:
        start_line = body.count("\n", 0, gm.start()) + 1
        end_line = body.count("\n", 0, gm.end()) + 1
        genblock_lines = set(range(start_line, end_line + 1))
    dropdown_lines = check_inforce.dropdown_lines(text)

    # Walk the body as blank-line-delimited blocks, each block a list of
    # (line_text, 1-based_line_number, absolute_offset_in_body) triples, to
    # classify a whole block at once while keeping each line's real offset
    # (blank-line separators still occupy space in `body` and must count).
    lines = body.splitlines(keepends=True)
    blocks: list[list[tuple[str, int, int]]] = [[]]
    pos = 0
    for i, line in enumerate(lines, start=1):
        if line.strip() == "":
            if blocks[-1]:
                blocks.append([])
        else:
            blocks[-1].append((line, i, pos))
        pos += len(line)
    if not blocks[-1]:
        blocks.pop()

    seen: dict[str, set[str]] = {}  # H2 -> titles already linked in it
    current_h2 = ""
    edits: list[tuple[int, int, str]] = []  # (start, end, replacement) in `body`
    for bi, block in enumerate(blocks):
        block_text = "".join(ln for ln, _, _ in block)
        block_start = block[0][2]
        h2m = H2_RE.match(block_text)
        if h2m:
            current_h2 = h2m.group(1)
            continue
        if is_heading_line(block_text):
            continue
        if any(is_table_line(ln) for ln, _, _ in block):
            continue
        if any(lineno in dropdown_lines for _, lineno, _ in block):
            continue
        if any(lineno in genblock_lines for _, lineno, _ in block):
            continue
        # A block quote's straight or smart quotes can pair up, after
        # check_preserved.py's own whitespace flattening, with an unrelated
        # quote mark in an *adjacent* paragraph and make that tool see a
        # bogus "quotation" spanning both -- so a paragraph immediately
        # next to a block quote is treated the same as one inside a
        # quotation itself (never touched).
        prev_bq = bi > 0 and any(is_blockquote_line(ln) for ln, _, _ in blocks[bi - 1])
        next_bq = bi + 1 < len(blocks) and any(
            is_blockquote_line(ln) for ln, _, _ in blocks[bi + 1]
        )
        if prev_bq or next_bq or any(is_blockquote_line(ln) for ln, _, _ in block):
            continue
        masked = mask_quotes(block_text)
        sentences: list[tuple[int, int]] = []
        pos = 0
        for m in SENT_SPLIT_RE.finditer(masked):
            sentences.append((pos, m.start()))
            pos = m.end()
        sentences.append((pos, len(masked)))
        h2_seen = seen.setdefault(current_h2, set())
        for s_start, s_end in sentences:
            sentence = masked[s_start:s_end]
            for lab, (title, url) in titles.items():
                if title in h2_seen:
                    continue
                if not re.search(r"\[\^" + re.escape(lab) + r"\](?!:)", sentence):
                    continue
                tm = None
                norm_title = re.sub(r"\s+", " ", title)
                for cand in ITALIC_RE.finditer(sentence):
                    # Normalise whitespace only for the comparison: a title
                    # wrapped across a line break by hard-wrapping is still
                    # the same title, but the replacement keeps the original
                    # text (with its line break) untouched otherwise.
                    if re.sub(r"\s+", " ", cand.group(1)) == norm_title:
                        tm = cand
                        break
                if tm is None:
                    continue
                abs_start = block_start + s_start + tm.start()
                abs_end = block_start + s_start + tm.end()
                if already_linked(body, abs_start, abs_end):
                    # This occurrence already carries a link (an earlier run,
                    # or another rule entirely) -- it still counts as *the*
                    # first occurrence of this title in this H2, so a later,
                    # unlinked occurrence further down the same H2 must not
                    # be linked on a subsequent run. Record it as seen, but
                    # make no edit.
                    h2_seen.add(title)
                    continue
                edits.append((abs_start, abs_end, f"[{tm.group(0)}](<{url}>)"))
                h2_seen.add(title)
                counts[lab] = counts.get(lab, 0) + 1
                counts["linked"] += 1

    edits.sort(key=lambda e: e[0], reverse=True)
    new_body = body
    for start, end, replacement in edits:
        new_body = new_body[:start] + replacement + new_body[end:]
    new_text = new_body + text[len(body) :]
    return new_text, counts


def target_files(paths: list[str]) -> list[Path]:
    if paths:
        return [Path(p).resolve() for p in paths]
    return sorted(
        p
        for p in DOCS.rglob("*.md")
        if "plans" not in p.relative_to(DOCS).parts
        and "references" not in p.relative_to(DOCS).parts
    )


def run(paths: list[str], check: bool) -> int:
    total = 0
    changed_files: list[Path] = []
    for path in target_files(paths):
        text = path.read_text(encoding="utf-8")
        new_text, counts = process_text(text)
        total += counts["linked"]
        if new_text != text:
            changed_files.append(path)
            if not check:
                path.write_text(new_text, encoding="utf-8")
    print(f"{len(changed_files)} files {'would change' if check else 'changed'}")
    print(f"linked: {total}")
    if check:
        for f in changed_files:
            print(f"would change: {f.relative_to(ROOT)}")
        return 1 if changed_files else 0
    return 0


# --------------------------------------------------------------------------


def selftest() -> int:
    problems: list[str] = []

    def fail(msg: str) -> None:
        problems.append(msg)

    def page(body: str, defs: str) -> str:
        return f"# T\n\n{body}\n{defs}"

    # The report's own example.
    p = page(
        "## Design rules\n\n"
        "The PDK's *Periphery rules* page gives difftap.3 = 0.270 "
        "µm.[^pdk-periph]\n",
        "[^pdk-periph]: SkyWater PDK, *Periphery rules*. "
        "<https://example.com/periph>\n",
    )
    new, counts = process_text(p)
    if counts.get("linked") != 1:
        fail(f"the report's own example did not link: {counts}")
    if "[*Periphery rules*](<https://example.com/periph>)" not in new:
        fail(f"wrong link produced: {new!r}")
    if "[^pdk-periph]" not in new:
        fail("the marker was disturbed")

    # Idempotent.
    new2, counts2 = process_text(new)
    if new2 != new or counts2.get("linked", 0):
        fail(f"not idempotent: {counts2}")

    # First occurrence per H2 only: a second co-occurrence of the same
    # title and marker in the same H2 is left alone.
    p = page(
        "## Design rules\n\n"
        "The PDK's *Periphery rules* page gives difftap.3 = 0.270 "
        "µm.[^pdk-periph] Later, the PDK's *Periphery rules* page also "
        "gives poly.2 = 0.210 µm.[^pdk-periph]\n",
        "[^pdk-periph]: SkyWater PDK, *Periphery rules*. "
        "<https://example.com/periph>\n",
    )
    new, counts = process_text(p)
    if counts.get("linked") != 1:
        fail(f"first-occurrence-per-H2 fired more than once: {counts}")
    if new.count("[*Periphery rules*]") != 1:
        fail(f"the second occurrence was linked too: {new!r}")
    # And running it again must not link the second occurrence either: an
    # already-linked occurrence still has to count as "seen" for its H2, or
    # a second run links the next occurrence down and ends up with two
    # links for one title in one H2 (found on docs/masks/pwdem.md, where
    # the site-wide run left the *second* Deep-dive-shaped mention in
    # "Drawn layers and derivation" for a later pass to wrongly pick up).
    new2, counts2 = process_text(new)
    if new2 != new or counts2.get("linked", 0):
        fail(f"a second run linked the later occurrence: {counts2} {new2!r}")

    # A new H2 gets its own first occurrence.
    p = page(
        "## A\n\nThe PDK's *Periphery rules* page gives one "
        "value.[^pdk-periph]\n\n"
        "## B\n\nThe PDK's *Periphery rules* page gives another "
        "value.[^pdk-periph]\n",
        "[^pdk-periph]: SkyWater PDK, *Periphery rules*. "
        "<https://example.com/periph>\n",
    )
    new, counts = process_text(p)
    if counts.get("linked") != 2:
        fail(f"a new H2 did not get its own first occurrence: {counts}")

    # Title and marker in *different* sentences: not linked.
    p = page(
        "## A\n\nThe PDK's *Periphery rules* page sets the design "
        "rules. A separate measurement confirms the value.[^pdk-periph]\n",
        "[^pdk-periph]: SkyWater PDK, *Periphery rules*. "
        "<https://example.com/periph>\n",
    )
    new, counts = process_text(p)
    if new != p or counts.get("linked", 0):
        fail(f"cross-sentence co-occurrence was wrongly linked: {new!r}")

    # Never inside a quotation.
    p = page(
        '## A\n\nThe filing states "see the *Periphery rules* page for '
        'details".[^pdk-periph]\n',
        "[^pdk-periph]: SkyWater PDK, *Periphery rules*. "
        "<https://example.com/periph>\n",
    )
    new, counts = process_text(p)
    if new != p or counts.get("linked", 0):
        fail(f"a title inside a quotation was linked: {new!r}")

    # Never inside a table (header or data row).
    p = page(
        "## A\n\n"
        "| Source | Note |\n"
        "|---|---|\n"
        "| The PDK's *Periphery rules* page | 0.270 µm.[^pdk-periph] |\n",
        "[^pdk-periph]: SkyWater PDK, *Periphery rules*. "
        "<https://example.com/periph>\n",
    )
    new, counts = process_text(p)
    if new != p or counts.get("linked", 0):
        fail(f"a title inside a table was linked: {new!r}")

    # Never inside a {dropdown}.
    p = page(
        "## A\n\n"
        ":::{dropdown} From a patent shown as in force (US 1,234,567; "
        "estimated expiry 2030-01-01) — open to read\n"
        "The PDK's *Periphery rules* page also matters here.[^pdk-periph]\n"
        ":::\n",
        "[^pdk-periph]: SkyWater PDK, *Periphery rules*. "
        "<https://example.com/periph>\n",
    )
    new, counts = process_text(p)
    if new != p or counts.get("linked", 0):
        fail(f"a title inside a dropdown was linked: {new!r}")

    # Never inside the generated index-links block.
    p = (
        "# T\n\n## A\n\n"
        "<!-- index-links:begin (generated by tools/gen_index_links.py; do not edit) -->\n"
        "### Related patents\n\n"
        "The PDK's *Periphery rules* page is cited here too.[^pdk-periph]\n"
        "<!-- index-links:end -->\n\n"
        "[^pdk-periph]: SkyWater PDK, *Periphery rules*. "
        "<https://example.com/periph>\n"
    )
    new, counts = process_text(p)
    if new != p or counts.get("linked", 0):
        fail(f"a title inside the generated block was linked: {new!r}")

    # Never in a paragraph next to a block quote (check_preserved.py's own
    # whitespace flattening can pair a quote mark in the block quote with
    # an unrelated one elsewhere on the page and read the paragraph in
    # between as part of a bogus "quotation" -- docs/machines/single-wafer
    # -spin-processor.md:161-166 is the real case that found this).
    p = page(
        'SkyWater\'s *Facilities & Capabilities* page lists:[^pdk-periph]\n\n'
        '> "Single Wafer"\n> "SEZ223, titration controlled"\n',
        "[^pdk-periph]: SkyWater PDK, *Facilities & Capabilities*. "
        "<https://example.com/periph>\n",
    )
    new, counts = process_text(p)
    if new != p or counts.get("linked", 0):
        fail(f"a paragraph beside a block quote was linked: {new!r}")

    # Never past "## References" (that's C1's territory).
    p = (
        "# T\n\n## References\n\n### Deep dive\n\n"
        "* The PDK's *Periphery rules* page — design rules.[^pdk-periph]\n\n"
        "[^pdk-periph]: SkyWater PDK, *Periphery rules*. "
        "<https://example.com/periph>\n"
    )
    new, counts = process_text(p)
    if new != p or counts.get("linked", 0):
        fail(f"a reading-list bullet was touched: {new!r}")

    # A prose bullet's own leading "* " is never mistaken for an italic
    # opening delimiter (it would otherwise "open" on the bullet marker
    # and "close" on the real title's own opening "*", eating it).
    p = page(
        "* The PDK's *Periphery rules* page gives a value.[^pdk-periph]\n",
        "[^pdk-periph]: SkyWater PDK, *Periphery rules*. "
        "<https://example.com/periph>\n",
    )
    new, counts = process_text(p)
    if counts.get("linked") != 1:
        fail(f"a prose bullet's leading '* ' broke italic matching: {counts}")
    if "[*Periphery rules*](<https://example.com/periph>)" not in new:
        fail(f"a prose bullet's title was mislinked: {new!r}")

    # A "**bold**" run near the marker is never mistaken for an italic
    # title (docs/steps/004-fom.md: "**The FOM reticle** ...[^thung-2016]"
    # next to an unrelated *Some paper* citation on the same page).
    p = page(
        "## A\n\n**The FOM reticle** is a chrome-on-quartz "
        "photomask.[^thung-2016] Elsewhere, *Some paper* gives a different "
        "value.[^some-paper]\n",
        "[^thung-2016]: Thung et al., *Some paper*. "
        "<https://example.com/thung>\n"
        "[^some-paper]: Thung et al., *Some paper*. "
        "<https://example.com/thung>\n",
    )
    new, counts = process_text(p)
    if "The FOM reticle" in "".join(
        m.group(1) for m in ITALIC_RE.finditer(new)
    ):
        fail(f"a bold run was matched as an italic title: {new!r}")
    if new.count("](<https://example.com/thung>)") != 1:
        fail(f"the real italic title was not linked exactly once: {new!r}")

    # A title wrapped across a line break is still matched.
    p = page(
        "## A\n\nThe PDK's *Periphery\nrules* page gives a "
        "value.[^pdk-periph]\n",
        "[^pdk-periph]: SkyWater PDK, *Periphery rules*. "
        "<https://example.com/periph>\n",
    )
    new, counts = process_text(p)
    if counts.get("linked") != 1:
        fail(f"a title wrapped across a line break was not linked: {counts}")
    if "[*Periphery\nrules*](<https://example.com/periph>)" not in new:
        fail(f"the wrapped title was mishandled: {new!r}")

    if problems:
        for p_ in problems:
            print("FAIL:", p_)
        return 1
    print("selftest OK")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="report only, write nothing")
    ap.add_argument("--selftest", action="store_true", help="run offline unit tests")
    ap.add_argument("paths", nargs="*")
    args = ap.parse_args()
    if args.selftest:
        return selftest()
    return run(args.paths, args.check)


if __name__ == "__main__":
    sys.exit(main())
